name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Set JVM Target to 11
        run: |
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g -Dkotlin.compiler.jvmTarget=11" >> gradle.properties

      - name: Run Lint
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            app/build/outputs/apk/Staging/debug/*.apk
            app/build/outputs/apk/debug/*.apk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
